name: Build and Release Plugin ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set plugin name
        id: vars
        run: echo "PLUGIN_NAME=native-social-share-wp" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          zip -r native-social-share-wp.zip . -x "*.git*" -x "*.github*" -x "*.DS_Store*" -x "*/__MACOSX/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGIN_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

